-- qris_merchants is the static-QRIS merchant registry. Unlike dynamic QRIS
-- (a row in payment_methods matched by partnerReferenceNo), a static QRIS
-- merchant owns ONE permanent QR string that is printed/displayed; inbound
-- payments carry no partnerReferenceNo and are matched back to the merchant by
-- store_id (NMID on Nobu side / storeId on Pakailink side).
--
-- Pakailink merchants are registered + QR-generated via API. Nobu merchants are
-- registered through a manual Excel form (no register API) and their qris_string
-- is pasted in by an operator. store_id is ALWAYS entered manually because it is
-- the key used to verify which merchant an inbound webhook belongs to. The other
-- descriptive fields (nmid, terminal_id, merchant_name, merchant_city, mcc) are
-- parsed automatically from the QR string when present.
CREATE TABLE IF NOT EXISTS qris_merchants (
    id                     BIGSERIAL PRIMARY KEY,
    client_id              INT REFERENCES clients(id) ON DELETE SET NULL, -- owning brand (nullable)
    provider               VARCHAR(20) NOT NULL,                          -- pakailink | nobu
    merchant_name          VARCHAR(64),                                   -- parsed from QR tag 59
    merchant_city          VARCHAR(64),                                   -- parsed from QR tag 60
    merchant_category_code VARCHAR(8),                                    -- parsed from QR tag 52
    nmid                   VARCHAR(32),                                   -- parsed from QR tag 51 subfield 02
    store_id               VARCHAR(64) NOT NULL,                          -- MANUAL: webhook identification key
    terminal_id            VARCHAR(32),                                   -- GERBANG-style; parsed from QR tag 62 subfield 07
    qris_string            TEXT,                                          -- static QR content (nullable until filled)
    status                 VARCHAR(16) NOT NULL DEFAULT 'active',         -- active | inactive
    raw_provider_response  JSONB,                                         -- Pakailink register/generate raw response
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One merchant per provider+store_id; webhook lookup relies on this being unique.
CREATE UNIQUE INDEX IF NOT EXISTS uq_qris_merchant_store
    ON qris_merchants (provider, store_id);

CREATE INDEX IF NOT EXISTS idx_qris_merchant_client
    ON qris_merchants (client_id, created_at DESC);

-- qris_payments records successful QRIS payments delivered via provider webhook.
-- A static QR has no partnerReferenceNo, so idempotency keys on (provider,
-- reference_no) — the provider-generated reference that is unique per payment.
CREATE TABLE IF NOT EXISTS qris_payments (
    id                   BIGSERIAL PRIMARY KEY,
    qris_merchant_id     BIGINT REFERENCES qris_merchants(id) ON DELETE SET NULL,
    provider             VARCHAR(20) NOT NULL,            -- pakailink | nobu
    reference_no         VARCHAR(64) NOT NULL,            -- provider reference (idempotency key)
    partner_reference_no VARCHAR(64),                     -- empty for static QR
    rrn                  VARCHAR(32),                     -- retrieval reference number
    payment_reference_no VARCHAR(64),                     -- reference generated by acquirer
    issuer_id            VARCHAR(16),
    store_id             VARCHAR(64) NOT NULL,            -- echoed from webhook (matches merchant)
    terminal_id          VARCHAR(32),
    amount               BIGINT NOT NULL,
    fee_amount           BIGINT,
    nett_amount          BIGINT,
    payer_name           VARCHAR(64),
    payer_phone          VARCHAR(32),
    status               VARCHAR(16) NOT NULL DEFAULT 'Success',
    paid_at              TIMESTAMPTZ,
    raw_payload          JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Idempotency: a repeated webhook for the same provider reference is a no-op.
CREATE UNIQUE INDEX IF NOT EXISTS uq_qris_payment_ref
    ON qris_payments (provider, reference_no);

CREATE INDEX IF NOT EXISTS idx_qris_payment_merchant
    ON qris_payments (qris_merchant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_qris_payment_store
    ON qris_payments (store_id, created_at DESC);
