-- Migration 042: QRIS provider is configured via admin panel (payment_methods.provider field).
-- No schema changes needed — a single QRIS/MPM row exists and its provider is
-- switched from the admin UI. This migration is intentionally a no-op.
